routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes(['verify'=>true]);

Route::get('/add/etablissement', 'HomeController@addEtablissement');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@getSearch');

Route::get('/detail/{slug}/{date_start}/{date_end}', 'HomeController@getDetail')->name('getdetails');

Route::get('liste', 'HomeController@getliste')->name('getlistes'); //liste Appartement

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::get('/commandes', 'DashboardController@getCommande')->name('commande');

Route::get('/settings', 'DashboardController@getSetting')->name('setting');

Route::get('/blog/{slug}', 'HomeController@getBlog'); //liste Appartement

Route::get('/contact', 'HomeController@getContact'); //liste Appartement

Route::post('/send/contact', 'HomeController@postContact'); //liste Appartement

//Lien Faire Reservation
Route::get('reservation/{slug}/{date_start}/{date_end}', 'ReservationController@faireReservation')->name('faireReservations');

Route::get('reservation/{commande}/terminate', 'ReservationController@terminateReservation');


Route::get('/image/delete/{id}', 'HomeController@destroyImage'); //liste Appartement

Route::post('/filtre/search/engine', 'HomeController@filterData');


Route::post('data/uploads/images', 'HomeController@postUploadImage'); //liste Appartement

Route::group(['namespace' => 'Admin', 'prefix' => 'admin','middleware' => 'admin'], function () {

    Route::get('/', 'HomeController@index');

    Route::get('orders/{id}/confirm-order', 'HomeController@confirmOrder');
    Route::get('orders/{id}/start-order', 'HomeController@startOrder');
    Route::get('orders/{id}/cancel-order', 'HomeController@cancelOrder');
    Route::get('orders/{id}/done', 'HomeController@done');
    Route::get('orders/{id}/invoice', 'HomeController@getInvoice');

});

Route::post('save/user/order', 'HomeController@saveOrderPost'); //liste Appartement


Route::resource('products', 'ProductController');

Route::resource('users', 'UserController');

Route::resource('orders', 'OrderController');

Route::resource('rooms', 'RoomController');

Route::get('/rooms/create/{id}', 'RoomController@create')->name('rooms.create.find');

Route::resource('typeChambres', 'TypeChambreController');

Route::resource('typeBeds', 'TypeBedController');

Route::resource('optionItems', 'OptionItemController');

Route::resource('feeds', 'FeedController');



//ApiController
Route::get('/api/room/{id}', 'ApiController@getRoom'); //liste Appartement

Route::post('/api/register/user', 'ApiController@addUser');
Route::post('/api/login/user', 'ApiController@loginUser');


Route::resource('customers', 'CustomerController');


Route::resource('invoices', 'InvoiceController');

Route::resource('suppliers', 'SupplierController');


Route::get('sendemail', function () {
    $data = array(
        'name' => "Ahoko Rent Test",
    );
    Mail::send('emails.test', $data, function ($message) {
        $message->to('jacques.bagui@gmail.com')->subject('Location vehicule Ahoko Rent');
    });
    return "Message Envoyé avec success";
});



Route::get('/foo', function () {
    Artisan::call('storage:link');
});

app/Models/TypeBed.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TypeBed
 * @package App\Models
 * @version June 3, 2019, 10:49 am UTC
 *
 * @property string name
 * @property integer status
 */
class TypeBed extends Model
{
    use SoftDeletes;

    public $table = 'type_beds';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'status' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/TypeBedController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTypeBedRequest;
use App\Http\Requests\UpdateTypeBedRequest;
use App\Repositories\TypeBedRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TypeBedController extends AppBaseController
{
    /** @var  TypeBedRepository */
    private $typeBedRepository;

    public function __construct(TypeBedRepository $typeBedRepo)
    {
        $this->typeBedRepository = $typeBedRepo;
    }

    /**
     * Display a listing of the TypeBed.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $typeBeds = $this->typeBedRepository->all();

        return view('type_beds.index')
            ->with('typeBeds', $typeBeds);
    }

    /**
     * Show the form for creating a new TypeBed.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_beds.create');
    }

    /**
     * Store a newly created TypeBed in storage.
     *
     * @param CreateTypeBedRequest $request
     *
     * @return Response
     */
    public function store(CreateTypeBedRequest $request)
    {
        $input = $request->all();

        $typeBed = $this->typeBedRepository->create($input);

        Flash::success('Type Bed saved successfully.');

        return redirect(route('typeBeds.index'));
    }

    /**
     * Display the specified TypeBed.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeBed = $this->typeBedRepository->find($id);

        if (empty($typeBed)) {
            Flash::error('Type Bed not found');

            return redirect(route('typeBeds.index'));
        }

        return view('type_beds.show')->with('typeBed', $typeBed);
    }

    /**
     * Show the form for editing the specified TypeBed.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeBed = $this->typeBedRepository->find($id);

        if (empty($typeBed)) {
            Flash::error('Type Bed not found');

            return redirect(route('typeBeds.index'));
        }

        return view('type_beds.edit')->with('typeBed', $typeBed);
    }

    /**
     * Update the specified TypeBed in storage.
     *
     * @param int $id
     * @param UpdateTypeBedRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTypeBedRequest $request)
    {
        $typeBed = $this->typeBedRepository->find($id);

        if (empty($typeBed)) {
            Flash::error('Type Bed not found');

            return redirect(route('typeBeds.index'));
        }

        $typeBed = $this->typeBedRepository->update($request->all(), $id);

        Flash::success('Type Bed updated successfully.');

        return redirect(route('typeBeds.index'));
    }

    /**
     * Remove the specified TypeBed from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeBed = $this->typeBedRepository->find($id);

        if (empty($typeBed)) {
            Flash::error('Type Bed not found');

            return redirect(route('typeBeds.index'));
        }

        $this->typeBedRepository->delete($id);

        Flash::success('Type Bed deleted successfully.');

        return redirect(route('typeBeds.index'));
    }
}

resources/views/type_beds/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Bed
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'typeBeds.store']) !!}

                        @include('type_beds.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_beds/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Bed
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($typeBed, ['route' => ['typeBeds.update', $typeBed->id], 'method' => 'patch']) !!}

                        @include('type_beds.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/type_beds/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('typeBeds.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/type_beds/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Type Beds</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('typeBeds.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('type_beds.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/type_beds/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Bed
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('type_beds.show_fields')
                    <a href="{!! route('typeBeds.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_beds/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $typeBed->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $typeBed->name !!}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{!! $typeBed->status !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $typeBed->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $typeBed->updated_at !!}</p>
</div>

resources/views/type_beds/table.blade.php
<div class="table-responsive">
    <table class="table" id="typeBeds-table">
        <thead>
            <tr>
                <th>Name</th>
        <th>Status</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($typeBeds as $typeBed)
            <tr>
                <td>{!! $typeBed->name !!}</td>
            <td>{!! $typeBed->status !!}</td>
                <td>
                    {!! Form::open(['route' => ['typeBeds.destroy', $typeBed->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('typeBeds.show', [$typeBed->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('typeBeds.edit', [$typeBed->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>